REATE OR REPLACE VIEW USER_NOTICE_HISTORY_VIEW AS 
	SELECT UNL.ID
		, UNL.USER_ID
		, UNL.STATUS
		, UNL.ACCEPT_TIME 
		, UNL.PAGE_NAME
		, DT.NAME
		, DT.CELL_PHONE
		, LU.LOGIN_NAME
	FROM USER_NOTICE_LOG UNL
		LEFT JOIN DRIVE_TRAINEE DT ON UNL.USER_ID = DT.ID
		LEFT JOIN LOGIN_USER LU ON LU.ID = DT.ID;
