CREATE OR REPLACE VIEW USER_NOTICE_HISTORY_V AS 
	SELECT UNL.ID
		, UNL.USER_ID
		, UNL.STATUS
		, UNL.ACCEPT_TIME 
		, UNL.PAGE_NAME
		, DT.NAME
		, DT.CELL_PHONE
		, LU.LOGIN_NAME
		, PL.ID NOTICE_ID
	FROM USER_NOTICE_LOG UNL
		LEFT JOIN DRIVE_TRAINEE DT ON UNL.USER_ID = DT.ID
		LEFT JOIN LOGIN_USER LU ON LU.ID = DT.ID
		LEFT JOIN PUSH_LOG PL ON UNL.PAGE_NAME = PL.PAGE_NAME
