CREATE VIEW USER_NOTICE_HISTORY_VIEW AS 
	SELECT UNL.ID
		, UNL.USER_ID
		, UNL.STATUS
		, UNL.ACCEPT_TIME 
		, UNL.PAGE PAGE_NAME
		, DT.NAME
		, DT.CELL_PHONE
	FROM USER_NOTICE_LOG UNL
		LEFT JOIN DRIVE_TRAINEE DT ON UNL.USER_ID = DT.ID;